---
# destroy instances

- name: destroying slurm instances 
  hosts: localhost
  connection: local
  vars_files:
      - group_vars/slurm/vars
      - group_vars/slurm/secret_vars
  
  vars:
    count: '{{ cluster_size - 1 }}'

  tasks:
  - name: deleting instances except provisioner
    linode.cloud.instance:
      label: '{{ instance_prefix }}{{ item | int + 1 }}-{{ uuid }}'
      api_token: '{{ token }}'
      state: absent
    with_sequence: count='{{ count }}'