---
- name: update /etc/hosts
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} SLURM HOSTS"
    block: |
      #jinja2: trim_blocks:False
      {%- for count in range(cluster_size) %}
      {{ slurm_data.server[count].instance.ip_priv1 }} {{ slurm_data.server[count].instance.hostname }}
      {%- endfor %}

- name: configure hostnames
  hostname:
    use: systemd
    name: "{{ slurm_data.server[count].instance.hostname }}"
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['slurm_servers'] }}"
  loop_control:
    index_var: count

- name: Set timezone to Bangkok
  shell: timedatectl set-timezone Asia/Bangkok

- name: Set root public key
  shell: echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCeePPLdTw2CRFEBtcU2pJgtSiCQunYzK2ZjZbKcOphX5pKdkCzTzQbP7LKWpq4ZqDZhwSJt4fEvN/zeiqCav5QPujbofQtEyHIY6yuSqXeO3wEEhXxTSyiox8TBjgn+1b5dCDK8ufu+FbHug8cC8PjiEMyemRAPM2oh9/VfV9eob1RWU64pZCNCPqNbutDbru13V/kP5NLkF1EK3L6q6pdeG/4BZXacV4sqYfoMUmz7VOgYnc2aa8ntqPi31F8cIjsOCxMmd+tXE/+MIf3Q/3vsUPwAW/yukUC7pckpuv9qeEpA+UyUR4mPRrd27vb0fKdrqPuhqy3cQARrcp0wrPEPNRu+bq92je6lrRjcQK97Pe97//RXZnAOBGZpB6xt4b6SIFGOUPiHcWR07wptuXF5vQkY5PBPbOR+um1XFDEWPxGi5PwVYHjcG3t7TJdyxectgHC4pqC7q+0nP8yqu0Wx95pJyt7P+g553uM2gvH/7IcWUeL9zR/hm3AZihA2V0= root@wrf_linode" >> /root/.ssh/authorized_keys
  shell: echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCeePPLdTw2CRFEBtcU2pJgtSiCQunYzK2ZjZbKcOphX5pKdkCzTzQbP7LKWpq4ZqDZhwSJt4fEvN/zeiqCav5QPujbofQtEyHIY6yuSqXeO3wEEhXxTSyiox8TBjgn+1b5dCDK8ufu+FbHug8cC8PjiEMyemRAPM2oh9/VfV9eob1RWU64pZCNCPqNbutDbru13V/kP5NLkF1EK3L6q6pdeG/4BZXacV4sqYfoMUmz7VOgYnc2aa8ntqPi31F8cIjsOCxMmd+tXE/+MIf3Q/3vsUPwAW/yukUC7pckpuv9qeEpA+UyUR4mPRrd27vb0fKdrqPuhqy3cQARrcp0wrPEPNRu+bq92je6lrRjcQK97Pe97//RXZnAOBGZpB6xt4b6SIFGOUPiHcWR07wptuXF5vQkY5PBPbOR+um1XFDEWPxGi5PwVYHjcG3t7TJdyxectgHC4pqC7q+0nP8yqu0Wx95pJyt7P+g553uM2gvH/7IcWUeL9zR/hm3AZihA2V0= root@wrf_linode" > /root/.ssh/id_rsa.pub

- name: Set root private key
  shell: echo "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAnnjzy3U8NgkRRAbXFNqSYLUogkLp2MytmY2WynDqYV+aSnZAs080
Gz+yylqauGag2YcEibeHxLzf83oqgmr+UD7o26H0LRMhyGOsrkql3jt8BBIV8U0soqMfEw
Y4J/tW+XQgyvLn7vhWx7oPHAvD44hDMnpkQDzNqIff1X1fXqG9UVlOuKWQjQj6jW7rQ267
td1f5D+TS5BdRCty+quqXXhv+AWV2nFeLKmH6DFJs+1ToGJ3NmmvJ7aj4t9RfHCI7DgsTJ
nfrVxP/jCH90P977FD8AFv8rpFAu6XJKbr/anhKQPlMlEeJj0a3du729Hyna6j7oast3EA
Ea3KdMKzxDzUbvm6vdo3upa0Y3ECvez3ve//0V2ZwDgRmaQesbeG+kiBRjlD4h3FkdO8Kb
blxeb0JGOTwT2zkfrptVxQxFj8RouT8FWB43Bt7e0yXcsXnLYBwuKagu6vtJz/MqrtFsfe
aScrez/oOed7jNoLx/+yHFlHi/c0f4ZtwGYoQNldAAAFgHYr0mZ2K9JmAAAAB3NzaC1yc2
EAAAGBAJ5488t1PDYJEUQG1xTakmC1KIJC6djMrZmNlspw6mFfmkp2QLNPNBs/sspamrhm
oNmHBIm3h8S83/N6KoJq/lA+6Nuh9C0TIchjrK5Kpd47fAQSFfFNLKKjHxMGOCf7Vvl0IM
ry5+74Vse6DxwLw+OIQzJ6ZEA8zaiH39V9X16hvVFZTrilkI0I+o1u60Nuu7XdX+Q/k0uQ
XUQrcvqrql14b/gFldpxXiyph+gxSbPtU6BidzZprye2o+LfUXxwiOw4LEyZ361cT/4wh/
dD/e+xQ/ABb/K6RQLulySm6/2p4SkD5TJRHiY9Gt3bu9vR8p2uo+6GrLdxABGtynTCs8Q8
1G75ur3aN7qWtGNxAr3s973v/9FdmcA4EZmkHrG3hvpIgUY5Q+IdxZHTvCm25cXm9CRjk8
E9s5H66bVcUMRY/EaLk/BVgeNwbe3tMl3LF5y2AcLimoLur7Sc/zKq7RbH3mknK3s/6Dnn
e4zaC8f/shxZR4v3NH+GbcBmKEDZXQAAAAMBAAEAAAGAPW7qI8943gG53cNBEeaBpFfWMl
k6Sj9edQ58jFIlqkXjjEY3YsuriXyyFNv26tFuPaWnzrOFQHFv5/VOEWzk1brtjmdEP00R
ZZuuT4rErlglBXb1ZqviR9Iws7FPh8BZwS6Rn9t2qh8/lQG95cNx1vz1/9WOk5B+sXyq+x
o1JHxS5fxXFiGo3ePDLZz4OxXsUt5U1CkJMtvuLAUj96Ug0EdmMKIJq7sTJQE7nHmu9r9k
EeLaEA/8RMr60XJ9Jl6BOUzZBd4xnn9Oxm/0Fcfu92iDk8OO8Y60cofevBZ4fqXQCOT585
Tz/fAod8U23CE30xeiqGwd4KKL97VkDZCqkx+evDsiGvSq116K/EBW6Z1HsBdBRcQ14q76
Snu5TnocU4VFJGt8kunZMrFEdb83IMT+o+9Aa62379nzf3J/5pNqIFplHZHb3Q6G46Gk+a
25AZOB6L4KdNFuAwPUswspLPK0JeuG/+56cSaLikLYa5eucDlRS86cgOf1R4iGRSpJAAAA
wFV1BoW4YsoFB8gmK5L5jd4fr0pVIUGXNQ86Cu1NEaU8LrnLlXOaSaw9wX94Axq36lxKag
I3TZvp+ZydxJ01g4YcMNO/P+E4Nuu3FaGsO1OXWXVfVQFYAPj0O+0S5Z//X4euzAIoxKiv
0E8tzm8PZO5z6vyO4xEaD3M9X+vi7otU1WXHpfcmiAVRnC9xx74JdnjtAemYD2SSVI9mO/
T+o3vxI0Flxq1raXms2ggXCn5bj/uVTUFLGd9lkyQlHqQuxAAAAMEAuVNlBPkRNMbgH7Bf
UZJEsOPbnnv8Yqto7lzK4bcAOnbK+YqqMuJ7do+Pp82x4UNAdeF1713m28nVSQM+q6+1jE
hvpzrXO4KCLGYCKUkuO6H3+wPNJmIP6T46dFFT11gdfwd2T2+KqFCHaHyRnqeSTTp7mmTW
X7lU/LEZIQ2GPJ6v7Rq6PpSlpekXMLmQeuzQN1lWo9koCWseTNTtwI9VIGESVgl+gqGg1f
CdIHy+QleKN19xfEFmseM9vaPxAFQnAAAAwQDa5/q+HSdrDUrkN3ZwfalfIfAvbn2G7rIm
dkGr8Ny8ybOCttlVAvvksr019RA7kb1L+yaKJQ/PmO7oVSQmiQavUTfxJAL8nxzB0+Osh3
FrIrNeaVpMSkdTpvFE5w7dzfY2LLO53Cc8RrjoACzpN3YiW764uvZshOCNaOWVo0xNiJg0
4Oej8F2xM4tbMZIX4g+KJ9p1HBOL9G9c67iftv0wQt+8yPHCAnl0Her4Zt5Vywo13xQFB7
i6d7Iz1R79xNsAAAAHcm9vdEBzMAECAwQ=
-----END OPENSSH PRIVATE KEY-----" > /root/.ssh/id_rsa
shell: chmod 600 /root/.ssh/id_rsa
