---
- name: update /etc/hosts
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} SLURM HOSTS"
    block: |
      #jinja2: trim_blocks:False
      {%- for count in range(cluster_size) %}
      {{ slurm_data.server[count].instance.ip_priv1 }} {{ slurm_data.server[count].instance.hostname }}
      {%- endfor %}

- name: configure hostnames
  hostname:
    use: systemd
    name: "{{ slurm_data.server[count].instance.hostname }}"
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['slurm_servers'] }}"
  loop_control:
    index_var: count
    