---

- name: install libmunge-dev libmunge2 munge
  apt:
    pkg:
    - libmunge-dev
    - libmunge2
    - munge
    state: present

#- name: Copy slurm_servers group to a new variable without localhost
#  set_fact:
#    slurm_servers_no_localhost: "{{ groups['slurm_servers'] | difference(['localhost']) }}"

- name: install slurmd
  apt:
    pkg:
    - slurmd
    state: present
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ slurm_servers_no_localhost }}"
  loop_control:
    index_var: count

- name: Remove original /etc/slurm directory
  file:
    path: /etc/slurm
    state: absent

- name: Create symlink from /home/etc/slurm to /etc/slurm
  file:
    src: /home/etc/slurm
    dest: /etc/slurm
    state: link

- name: restart slurmd
  systemd:
    name: slurmd
    state: restarted
    enabled: yes
