---
- name: install nfsserver
  apt:
    name: nfs-kernel-server
    state: present
  delegate_to: "{{groups['slurm_servers'][0]}}"

- name: install nfsclient
  apt:
    name: nfs-common
    state: present

- name: add export entry for /home
  lineinfile:
    path: /etc/exports
    line: "/home 192.168.0.0/16(rw,sync,no_root_squash,no_subtree_check)"
  delegate_to: "{{groups['slurm_servers'][0]}}"

- name: restart nfs-kernel-server
  systemd:
    name: nfs-kernel-server
    state: restarted
    enabled: yes

- name: Mount NFS Share
  hosts: all
  become: true
  tasks:
    - name: Ensure mount point directory exists
      file:
        path: /home
        state: directory

    - name: Mount NFS share
      mount:
        src: "compute-01:/home"
        path: /home
        fstype: nfs
        opts: "defaults"
        state: mounted
      loop: "{{ groups['slurm_server'] | slice(1, groups['slurm_server'] | length) }}"
      delegate_to: "{{ item }}"

    - name: Ensure NFS share is mounted at boot
      mount:
        src: "compute-01:/home"
        path: /home
        fstype: nfs
        opts: "defaults"
        state: present
      loop: "{{ groups['slurm_server'] | slice(1, groups['slurm_server'] | length) }}"
      delegate_to: "{{ item }}"
