---

- name: install nfsserver
  apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes
  delegate_to: localhost

#- name: wait for apt process to finiupdate_cache: yessh
#  wait_for:
#    path: /var/lib/dpkg/lock  
#    state: absent 
#    timeout: 300