---
- name: install nfsserver
  apt:
    name: nfs-kernel-server
    state: present
  delegate_to: "{{groups['slurm_servers'][0]}}"

- name: wait for apt process to finish
  wait_for:
    path: /var/lib/dpkg/lock  
    state: absent 
    timeout: 300