---

- name: Copy slurm_servers group to a new variable without localhost
  set_fact:
    slurm_servers_no_localhost: "{{ groups['slurm_servers'] | difference(['localhost']) }}"

- name: install nfsclient
  apt:
    pkg:
    - nfs-common
    state: present
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ slurm_servers_no_localhost }}"
  loop_control:
    index_var: count

- name: Add NFS mount to fstab
  lineinfile:
    path: /etc/fstab
    line: "compute-01:/home /home nfs auto,timeo=14,intr 0 0"
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ slurm_servers_no_localhost }}"
  loop_control:
    index_var: count

- name: Mount NFS share 
  shell: mount -a 
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ slurm_servers_no_localhost }}"
  loop_control:
    index_var: count

