---

- name: install libmunge-dev libmunge2 munge
  apt:
    name: libmunge-dev libmunge2 munge
    state: present

#- name: restart munge
#  systemd:
#    name: munge
#    state: restarted
#    enabled: yes

#- name: Create directory in /home
#  file:
#    path: /home/etc
#    state: directory
#    mode: '0755'

#- name: Sync munge directory to /home/etc
#  command: rsync -av /etc/munge /home/etc/munge

#- name: Remove original /etc/munge directory
#  file:
#    path: /etc/munge
#    state: absent

#- name: Create symlink from /home/etc/munge to /etc/munge
#  file:
#    src: /home/etc/munge
#    dest: /etc/munge
#    state: link