---

- name: install slurmctld
  apt:
    pkg:
    - slurmctld
    - mailutils
    - slurmd 
    - mpich
    state: present

- name: Copy root ssh config
  template:
    src: templates/slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    mode: '0644'
    owner: "slurm"
    group: "slurm"

- name: Sync slurm directory to /home/etc
  command: rsync -av /etc/slurm /home/etc/

- name: Remove original /etc/slurm directory
  file:
    path: /etc/slurm
    state: absent

- name: Create symlink from /home/etc/slurm to /etc/slurm
  file:
    src: /home/etc/slurm
    dest: /etc/slurm
    state: link

- name: Copy slurm config
  template:
    src: templates/slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    mode: '0644'
    owner: "slurm"
    group: "slurm"

- name: restart slurmctld
  systemd:
    name: slurmctld
    state: restarted
    enabled: yes

- name: restart slurmd
  systemd:
    name: slurmd
    state: restarted
    enabled: yes