---
- name: adding sudo user
  import_tasks: sudouser.yml

- name: add user ssh keys
  import_tasks: sshkeys.yml

- name: writing slurm creds into file
  import_tasks: motd.yml

- name: set timezone 
  import_tasks: timezone.yml