- name: Run slurmd command and grep for NodeName
  shell: slurmd -C | grep NodeName
  register: slurmd_output
  run_once: true
  delegate_to: "localhost"

- name: Extract NodeName value
  set_fact:
    NodeName1: "{{ slurmd_output.stdout_lines[0] }}"
  when: slurmd_output.stdout_lines | length > 0
  run_once: true
  delegate_to: "localhost"

- name: get NodeName
  set_fact:
    node_range: "compute-[01-{{ '%02d' | format(cluster_size) }}]"
  run_once: true
  delegate_to: "localhost"

- name: Replace compute-01 with node_range
  set_fact:
    updated_NodeName: "{{ NodeName1.replace('compute-01', node_range) }}"
  run_once: true
  delegate_to: "localhost"

- name: new slurm config
  lineinfile:
    path: /etc/slurm/slurm.conf
    regexp: '^NodeName=.+'
    line: '{{ updated_NodeName }}'
  run_once: true
  delegate_to: "localhost"

- name: restart slurmctld
  systemd:
    name: slurmctld
    state: restarted
    enabled: yes
  run_once: true
  delegate_to: "localhost"

- name: restart slurmd
  systemd:
    name: slurmd
    state: restarted
    enabled: yes