---
# roles/post/tasks/sshkeys.yml

- name: get root password
  slurp:
    src: "/etc/shadow"
  run_once: true
  delegate_to: "localhost"
  register: shadow

- name: set root password
  set_fact:
    root_password: "{{ shadow['content'] | b64decode | regex_search('^root.+') }}"
  run_once: true
#  delegate_to: "localhost"

# set root account passwords
- name: set root password on remote nodes
  lineinfile:
    path: /etc/shadow
    regexp: '^root.+'
    line: '{{ root_password }}'

# set user passwords
- name: set user password
  lineinfile:
    path: /etc/shadow
    regexp: '^{{ username }}.+'
    line: '{{ root_password }}'


- name: set ssh facts
  set_fact:
    add_keys_prompt: '{{ add_keys_prompt }}'

- name: add account ssh keys
  copy:
    src: '{{ local_home }}/.ssh/authorized_keys'
    dest:  "{{ item.userdir }}/.ssh/authorized_keys"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: '0600'
  loop:
    - { userdir: '/root', user: 'root' }
    - { userdir: '/home/{{ username }}', user: '{{ username }}' }
  when: add_keys_prompt == 'yes'

#- name: remove ansible from authorized_keys
#  lineinfile:
#    dest: /root/.ssh/authorized_keys
#    state: absent
#    regexp: '^.+ansible$'

- name: copy ansible ssh keys to ssh key
  command:
    cmd: cp "{{ item.src }}" "{{ item.dest }}"
  run_once: true
  delegate_to: localhost
  loop:
    - { src: "{{ ansible_env.HOME }}/.ssh/id_ansible_ed25519", dest: "{{ ansible_env.HOME }}/.ssh/id_rsa" }
    - { src: "{{ ansible_env.HOME }}/.ssh/id_ansible_ed25519.pub", dest: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub" }

- name: Append public key to authorized_keys
  lineinfile:
    path: "{{ ansible_env.HOME }}/.ssh/authorized_keys"
    line: "{{ lookup('file', '{{ ansible_env.HOME }}/.ssh/id_rsa.pub') }}"
    state: present
  run_once: true
  delegate_to: localhost

- name: remove ansible ssh keys
  file:
    path: '{{ item }}'
    state: absent
  run_once: true
  delegate_to: localhost
  loop:
    - '{{ ansible_env.HOME }}/.ssh/id_ansible_ed25519'
    - '{{ ansible_env.HOME }}/.ssh/id_ansible_ed25519.pub'
  
#- name: Set root authorized_keys
#  template:
#    src: templates/authorized_keys.j2
#    dest: /root/.ssh/authorized_keys
#    mode: '0600'
#    owner: "root"
#    group: "root"

#- name: Copy root private key
#  template:
#    src: templates/id_rsa.j2
#    dest: /root/.ssh/id_rsa
#    mode: '0600'
#    owner: "root"
#    group: "root"

## set wrfroms account passwords
#- name: create user wrfroms
#  user:
#    name: wrfroms
#    password: "{{ 'test#123456' | password_hash('sha512') }}"
#    shell: /bin/bash

#- name: set wrfroms password on remote nodes
#  lineinfile:
#    path: /etc/shadow
#    regexp: '^wrfroms.+'
#    line: '{{ wrfroms_password }}'

#- name: create .ssh directory for wrfroms
#  file:
#    path: /home/wrfroms/.ssh
#    state: directory
#    mode: '0700'
#    owner: wrfroms
#    group: wrfroms

#- name: Set wrfroms authorized_keys
#  template:
#    src: /root/.ssh/authorized_keys
#    dest: /home/wrfroms/.ssh/authorized_keys
#    mode: '0600'
#    owner: "wrfroms"
#    group: "wrfroms"

#- name: Copy wrfroms private key
#  template:
#    src: /root/.ssh/id_rsa
#    dest: /home/wrfroms/.ssh/id_rsa
#    mode: '0600'
#    owner: "wrfroms"
#    group: "wrfroms"

#- name: Copy root ssh config
#  template:
#    src: templates/ssh.config.j2
#    dest: /root/.ssh/config
#    mode: '0644'
#    owner: "root"
#    group: "root"

#- name: Copy wrfroms ssh config
#  template:
#    src: templates/ssh.config.j2
#    dest: /home/wrfroms/.ssh/config
#    mode: '0644'
#    owner: "wrfroms"
#    group: "wrfroms"

#****************
#- name: replace root with wrfroms in wrfroms_password
#  set_fact:
#    wrfroms_password: "{{ root_password | replace('root', 'wrfroms') }}"